# Arch/AUR packages and Flatpaks offered by restore-dots.sh option 4.
# shellcheck disable=SC2034
EXTRA_PACKAGES=(
  jefferson
  yubico-authenticator-bin
  hashid
  python-ubi-reader-git
  rambox-pro-bin
)

EXTRA_FLATPAKS=(
  org.videolan.VLC
  org.gnome.Calculator
)

REMOVE_REPOSITORY_VLC=true
