# Service restore values copied into each SERV backup.

SMB_DIRS=(
  "/SMB"
  "/SMB/euclid"
  "/SMB/pneuma-kali"
  "/SMB/pneuma-win"
  "/SMB/lateralus"
  "/SMB/SCP"
  "/SMB/SCP/HDD-01"
  "/SMB/SCP/HDD-02"
  "/SMB/SCP/HDD-03"
)

GRUB_CMDLINE_LINUX_DEFAULT_VALUE="loglevel=3 quiet splash"
GRUB_TERMINAL_OUTPUT_VALUE="gfxterm"
GRUB_GFXMODE_VALUE="1440x1080x32"
GRUB_THEME_VALUE="/boot/grub/themes/lateralus/theme.txt"
